### ISSUE TITLE
class="postlink" - URLs still get parsed by ext

### ISSUE THREAD

**Issue by VOOM108** [Mar-tin-G/LocalUrlToText#10]
Hi! I hope you still monitor these issues; I have a smallish problem with this extension. It works fine in general, but internal links with the class "postlink" get parsed by the extension though they should not. 

This refers to links that a member posts with his own text like [url=http://…..]MyText[/url]

As far as I understand the code: Since those links do not get the class "postlink-local" (I checked) they should not be parsed. (line 168 in listener.php)

I have tried anything I could think of to make sure the MyText people want there stays intact. 

Also: many links (but not all) coming from a viewtopic - link where off the actual post they should refer to. I fixed this by always looking for #postid as all viewtopic-links get one anyway.

**Comment by VOOM108** [comment]
Through massive trial and error I have found a workaround to ensure only those links get rendered that have no url bbcode with linktext.… Also this fixes the 2nd issue explained above. 

```
case 'viewtopic':
						if (preg_match('/viewtopic/', $match['text'], $id))
						{
						if (preg_match('/#p(\d+)/', $match['params'], $id))
						{
							$this->ids_to_fetch['post'][] = $id[1];
							$matches[$k]['type'] = LOCALURLTOTEXT_TYPE_POST;
							$matches[$k]['id'] = $id[1];
						}
						else if (preg_match('/(?:\?|&|&amp;)t=(\d+)/', $match['params'], $id))
						{
							$this->ids_to_fetch['topic'][] = $id[1];
							$matches[$k]['type'] = LOCALURLTOTEXT_TYPE_TOPIC;
							$matches[$k]['id'] = $id[1];
						}
						}
					break;
```

**Comment by VOOM108** [comment]
Of course if you want a link to a forum also to show the manually added linktext, the same principle would apply to the first "case" like so:  if (preg_match('/viewforum/', $match['text'], $id))

**Comment by Galixte** [comment]
Hi @Mar-tin-G,

coud you take a look, please ?

**Comment by Galixte** [comment]
@Mar-tin-G bump, please. :)

**Comment by Mar-tin-G** [comment]
@VOOM108 thanks for bringing this issue up, I'll look into it.

**Comment by Galixte** [comment]
Thanks for fixing that issue. ;)
