### ISSUE TITLE
Handle UTF-8 characters properly

### ISSUE THREAD

**Issue by Mar-tin-G** [Mar-tin-G/LocalUrlToText#13]
see https://www.phpbb.com/community/viewtopic.php?p=14391081#p14391081

> Bad working witn non-english in setting (UTF8 may be problem)

Problem: when adding a UTF-8 char (example: `–` or `…`) to one of the placeholder setting inputs of the extension and saving the settings, the char is replaced by `???`.

Before save:

![localurltotext-utf8-issue-1](https://user-images.githubusercontent.com/10298907/36642681-7d061408-1a43-11e8-8c8a-e6c56d5b74b6.png)

After save:

![localurltotext-utf8-issue-2](https://user-images.githubusercontent.com/10298907/36642680-7ce264f4-1a43-11e8-996f-d33e96fbdc43.png)

**Comment by 3D-I** [comment]
https://github.com/Mar-tin-G/LocalUrlToText/blob/6f08f3f2f6acfb4f6eab69cfa436a9ae9ec76964/acp/main_module.php#L37 

example, set the third parameter to `true`

> $config->set('martin_localurltotext_user',  $request->variable('martin_localurltotext_user', '', true));

For each input which needs to adhere to UTF8

**Comment by Mar-tin-G** [comment]
Great @3D-I, this does the trick, thanks!

**Comment by 3D-I** [comment]
I see you are thanking not me lol

https://www.phpbb.com/community/viewtopic.php?p=14960001#p14960001
